# Generated by Django 5.0 on 2024-01-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phonenuber',
        ),
        migrations.AddField(
            model_name='register',
            name='phonenumber',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
